#pragma once

#include <array>
#include <cstdint>
#include <initializer_list>
#include <ostream>
#include <string>
#include <type_traits>

#include "math/geometry_model.h"

namespace ndyn::math {

template <typename T>
class ScalarTypes {
 public:
  using ScalarType = typename T::ScalarType;
};

template <>
class ScalarTypes<float> {
 public:
  using ScalarType = float;
};

template <>
class ScalarTypes<double> {
 public:
  using ScalarType = double;
};

/**
 * State vector of a particle or object for use in simulations. The meaning of the various elements
 * is unspecified. For standard mechanical systems, the position is in element zero, the velocity in
 * element one, acceleration in element two, etc., as needed.
 */
template <GeometryModel GeometryType, size_t DEPTH>
class State final {
 public:
  using Geometry = GeometryType;
  using Algebra = Geometry::Algebra;
  using VectorType = Geometry::Multivector;
  using ValueType = VectorType;
  using ScalarType = Geometry::Scalar;

 private:
  std::array<VectorType, DEPTH> elements_{};

 public:
  static constexpr size_t depth() { return DEPTH; }

  constexpr State() = default;
  constexpr State(const State& rhs) = default;
  constexpr State(State&& rhs) = default;

  constexpr State& operator=(const State& rhs) = default;
  constexpr State& operator=(State&& rhs) = default;

  constexpr State(std::initializer_list<VectorType> elements) {
    size_t i = 0;
    for (const auto& element : elements) {
      elements_.at(i) = element;
      ++i;
    }
  }

  template <size_t INDEX>
  constexpr const auto& element() const {
    static_assert(INDEX < DEPTH, "Attempt to reference out of bounds index");
    return elements_[INDEX];
  }

  constexpr const auto& element(size_t index) const { return elements_.at(index); }

  template <size_t INDEX>
  constexpr void set_element(const VectorType& element) {
    static_assert(INDEX < DEPTH, "Attempt to reference out of bounds index");
    elements_[INDEX] = element;
  }

  constexpr void set_element(size_t index, const VectorType& element) {
    elements_.at(index) = element;
  }

  /**
   * Performs a Lie-group aware update of the state, assuming that the pose (position and
   * orientation) is expressed as a motor (rotor, translator, dilator, and their combinations). This
   * method advances the state by treating the multivectors as elements of a fiber bundle where the
   * base manifold is the Lie Group of transformations. For index 0 (The Pose Motor): The update is
   * performed via the Exponential Map (M_new = exp(K*dt) * M_old). This is necessary because the
   * space of valid poses (the Lie Group) is non-linear and curved. Linear addition in this space
   * would violate the geometric constraints of the algebra—leading to "numerical shearing" or scale
   * drift. By using the exponential of the kinematic bivector, we ensure the state stays exactly on
   * the manifold of valid rotations, translations, and boosts. This effectively "rotates" the
   * entire coordinate frame along the flow generated by the bivector. For indices 1 and higher (The
   * Kinematic Derivatives): These elements reside in the Lie Algebra (the tangent space), which is
   * a linear vector space by definition. Because the algebra represents "rates of change" rather
   * than "positions," linear addition is the mathematically correct way to accumulate changes (such
   * as acceleration modifying velocity). These updates represent the straight-line translation of
   * the kinematic generators within the tangent plane before they are "wrapped" back onto the
   * manifold during the next index-0 update. This dual-mode advancement allows the system to remain
   * numerically stable and physically consistent across arbitrary time scales, naturally preserving
   * invariants like the speed of light in CSTA or the rigidity of transforms in PGA.
   */
  [[nodiscard]] State advance(const State& delta, ScalarType interval) const noexcept {
    State result{};

    // Index 0: Motor update M_new = exp(K * dt) * M_old
    // delta.element(0) here is the Kinematic Bivector (the derivative of the Motor)
    const VectorType kinematics{interval * delta.element<0>()};
    result.set_element<0>(Geometry::motor_exp(kinematics) * element<0>());

    // Index 1+: Linear updates in the Lie Algebra / Vector space
    for (size_t i = 1; i < DEPTH; ++i) {
      result.set_element(i, element(i) + interval * delta.element(i));
    }
    return result;
  }

  constexpr State shift() const {
    State result{};
    for (size_t i = 0; i < DEPTH - 1; ++i) {
      result.elements_[i] = elements_[i + 1];
    }
    return result;
  }
};

template <typename T, size_t DEPTH>
std::string to_string(const State<T, DEPTH>& state) {
  using std::to_string;
  std::string result{"{"};
  bool need_comma{false};
  for (size_t i = 0; i < DEPTH; ++i) {
    if (need_comma) {
      result.append(", ");
    }
    result.append(to_string(state.element(i)));
    need_comma = true;
  }
  result.append("}");
  return result;
}

template <typename T, size_t DEPTH>
std::ostream& operator<<(std::ostream& os, const State<T, DEPTH>& state) {
  using std::to_string;
  os << to_string(state);
  return os;
}

/**
 * StateBuilder aids in mapping from Euclidean initial conditions
 * to state multivectors according to the chosen geometry.
 */
template <typename GeometryT>
class StateBuilder final {
 public:
  using Geometry = GeometryT;
  using Multivector = typename Geometry::Multivector;
  using Scalar = typename Geometry::Scalar;

 private:
  // Initial Pose data
  Scalar time_origin_{};
  Scalar position_x_{};
  Scalar position_y_{};
  Scalar position_z_{};

  Scalar rotation_angle_{};
  std::array<Scalar, 3> rotation_axis_{0, 0, 1};  // Default to Z-axis

  // Kinematic rates
  Scalar velocity_x_{};
  Scalar velocity_y_{};
  Scalar velocity_z_{};

  Scalar angular_velocity_x_{};
  Scalar angular_velocity_y_{};
  Scalar angular_velocity_z_{};

  Scalar acceleration_x_{};
  Scalar acceleration_y_{};
  Scalar acceleration_z_{};

 public:
  void set_initial_time(Scalar t) noexcept { time_origin_ = t; }

  void set_position(Scalar x, Scalar y, Scalar z) noexcept {
    position_x_ = x;
    position_y_ = y;
    position_z_ = z;
  }

  void set_orientation(const std::array<Scalar, 3>& axis, Scalar angle_rad) noexcept {
    rotation_axis_ = axis;
    rotation_angle_ = angle_rad;
  }

  // --- Kinematics Configuration ---

  void set_linear_velocity(Scalar vx, Scalar vy, Scalar vz) noexcept {
    velocity_x_ = vx;
    velocity_y_ = vy;
    velocity_z_ = vz;
  }

  void set_angular_velocity(Scalar wx, Scalar wy, Scalar wz) noexcept {
    angular_velocity_x_ = wx;
    angular_velocity_y_ = wy;
    angular_velocity_z_ = wz;
  }

  void set_acceleration(Scalar ax, Scalar ay, Scalar az) noexcept {
    acceleration_x_ = ax;
    acceleration_y_ = ay;
    acceleration_z_ = az;
  }

  /**
   * Constructs the initial state multivectors.
   */
  template <size_t N>
  void build(State<Geometry, N>& out_state) const noexcept {
    // 1. Construct the Pose Motor: M = T * R
    const Multivector rotor = Geometry::make_rotor(rotation_axis_, rotation_angle_);
    const Multivector translator =
        Geometry::make_translator(time_origin_, position_x_, position_y_, position_z_);

    out_state.set_element<0>(translator * rotor);

    if constexpr (N > 1) {
      // 2. Construct the Kinematic Bivector: K = Ω + V + A
      Multivector kinematic{};

      // Angular Velocity (Spacelike Bivectors)
      kinematic += angular_velocity_x_ * Geometry::e23();
      kinematic += -angular_velocity_y_ * Geometry::e13();
      kinematic += angular_velocity_z_ * Geometry::e12();

      // Linear Velocity (Time-Space Bivectors)
      kinematic += velocity_x_ * Geometry::e01();
      kinematic += velocity_y_ * Geometry::e02();
      kinematic += velocity_z_ * Geometry::e03();

      // Acceleration (Conformal Bivectors)
      kinematic += acceleration_x_ * (Geometry::e1() * (Geometry::e_plus() - Geometry::e_minus()));
      kinematic += acceleration_y_ * (Geometry::e2() * (Geometry::e_plus() - Geometry::e_minus()));
      kinematic += acceleration_z_ * (Geometry::e3() * (Geometry::e_plus() - Geometry::e_minus()));

      out_state.set_element<1>(kinematic);
    }
  }
};

}  // namespace ndyn::math
