#include "ui/ast_printer.h"

#include <string>

#include "glog/logging.h"
#include "ui/grammar.h"

namespace ndyn::ui {

/**
 * Prints an AST generated by the Grammar.
 */
class AstPrinter final : public Visitor {
 private:
  int indent_{};

 public:
  void visit(LineAst&) override;

  void visit(StatementExpressionAst&) override;
  void visit(AssignmentAst&) override;

  void visit(ScalarAst&) override;
  void visit(IdentifierAst&) override;
  void visit(UnaryAst&) override;
  void visit(BinaryAst&) override;

  void visit(BinaryOpAst&) override;

  void visit(DictCommandAst&) override;
  void visit(ExitCommandAst&) override;
  void visit(HelpCommandAst&) override;

  void print(LineAst& line, int starting_indent);
};

void print_ast(LineAst& line, int starting_indent) {
  AstPrinter printer{};
  printer.print(line, starting_indent);
}

void AstPrinter::print(LineAst& line, int starting_indent) {
  indent_ = starting_indent;
  line.visit(*this);
  indent_ = 0;
}

void AstPrinter::visit(LineAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Line";
  ++indent_;
  // Visit children.
  if (node.statement) {
    node.statement->visit(*this);
  } else {
    LOG(INFO) << std::string(indent_ * 2, ' ') << "<empty>";
  }
  --indent_;
}

void AstPrinter::visit(StatementExpressionAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Top-level Expression";
  ++indent_;
  // Visit children.
  if (node.expression) {
    node.expression->visit(*this);
  } else {
    LOG(INFO) << std::string(indent_ * 2, ' ') << "<empty expression>";
  }
  --indent_;
}

void AstPrinter::visit(AssignmentAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Assignment";
  ++indent_;
  // Visit children.
  LOG(INFO) << std::string(indent_ * 2, ' ') << "[ID] '" << node.name << "'";
  if (node.value) {
    node.value->visit(*this);
  } else {
    LOG(INFO) << std::string(indent_ * 2, ' ') << "<empty expression>";
  }
  --indent_;
}

void AstPrinter::visit(ScalarAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Scalar";

  ++indent_;
  // Visit children.
  LOG(INFO) << std::string(indent_ * 2, ' ') << "[VALUE] " << node.value;
  --indent_;
}

void AstPrinter::visit(IdentifierAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Identifier";
  ++indent_;
  // Visit children.
  LOG(INFO) << std::string(indent_ * 2, ' ') << "[ID] '" << node.name << "'";
  --indent_;
}

void AstPrinter::visit(UnaryAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Unary";
  ++indent_;
  // Visit children.
  LOG(INFO) << std::string(indent_ * 2, ' ') << "[OP] '" << to_string(node.op) << "'";
  if (node.operand) {
    node.operand->visit(*this);
  } else {
    LOG(INFO) << std::string(indent_ * 2, ' ') << "<empty operand>";
  }
  --indent_;
}

void AstPrinter::visit(BinaryOpAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "BinaryOp";
  ++indent_;
  // Visit children.
  LOG(INFO) << std::string(indent_ * 2, ' ') << "[OP] '" << to_string(node.op) << "'";
  --indent_;
}

void AstPrinter::visit(BinaryAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Binary";
  ++indent_;
  // Visit children.
  LOG(INFO) << std::string(indent_ * 2, ' ') << "[OPERATOR]";
  ++indent_;
  if (node.op) {
    node.op->visit(*this);
  } else {
    LOG(INFO) << std::string(indent_ * 2, ' ') << "<empty operand>";
  }
  --indent_;
  LOG(INFO) << std::string(indent_ * 2, ' ') << "[LHS]";
  ++indent_;
  if (node.lhs) {
    node.lhs->visit(*this);
  } else {
    LOG(INFO) << std::string(indent_ * 2, ' ') << "<empty operand>";
  }
  --indent_;
  LOG(INFO) << std::string(indent_ * 2, ' ') << "[RHS]";
  ++indent_;
  if (node.rhs) {
    node.rhs->visit(*this);
  } else {
    LOG(INFO) << std::string(indent_ * 2, ' ') << "<empty operand>";
  }
  --indent_;
  --indent_;
}

void AstPrinter::visit(DictCommandAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Dict";
  ++indent_;
  // Visit children.
  --indent_;
}

void AstPrinter::visit(ExitCommandAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Exit";
}

void AstPrinter::visit(HelpCommandAst& node) {
  LOG(INFO) << std::string(indent_ * 2, ' ') << "Help";
}

}  // namespace ndyn::ui
